# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'calcAppUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):

    def incrEvent(self):
        value1 = int(self.lineEdit.text())
        value2 = int(self.lineEdit_2.text())
        total = value1 + value2
        self.lineEdit_3.setText(str(total))
        print("Summed")

    def subEvent(self):
        value1 = int(self.lineEdit.text())
        value2 = int(self.lineEdit_2.text())
        total = value1 - value2
        self.lineEdit_3.setText(str(total))
        print("Subtracted")

    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(377, 345)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.title_label = QtWidgets.QLabel(self.centralwidget)
        self.title_label.setGeometry(QtCore.QRect(40, 20, 331, 71))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.title_label.setFont(font)
        self.title_label.setObjectName("title_label")
        self.v1_label = QtWidgets.QLabel(self.centralwidget)
        self.v1_label.setGeometry(QtCore.QRect(60, 100, 55, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.v1_label.setFont(font)
        self.v1_label.setObjectName("v1_label")
        self.v2_label = QtWidgets.QLabel(self.centralwidget)
        self.v2_label.setGeometry(QtCore.QRect(60, 140, 55, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.v2_label.setFont(font)
        self.v2_label.setObjectName("v2_label")
        self.addButton = QtWidgets.QPushButton(self.centralwidget)
        self.addButton.setGeometry(QtCore.QRect(40, 190, 93, 28))
        self.addButton.setObjectName("addButton")
        self.subButton = QtWidgets.QPushButton(self.centralwidget)
        self.subButton.setGeometry(QtCore.QRect(160, 190, 93, 28))
        self.subButton.setObjectName("subButton")
        self.result_label = QtWidgets.QLabel(self.centralwidget)
        self.result_label.setGeometry(QtCore.QRect(60, 230, 55, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.result_label.setFont(font)
        self.result_label.setObjectName("result_label")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(160, 100, 113, 22))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lineEdit.setFont(font)
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_2.setGeometry(QtCore.QRect(160, 140, 113, 22))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lineEdit_2.setFont(font)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.lineEdit_3 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_3.setGeometry(QtCore.QRect(160, 230, 113, 22))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lineEdit_3.setFont(font)
        self.lineEdit_3.setObjectName("lineEdit_3")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 377, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.addButton.pressed.connect(self.incrEvent) # type: ignore
        self.subButton.pressed.connect(self.subEvent) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.title_label.setText(_translate("MainWindow", "Calculator Application"))
        self.v1_label.setText(_translate("MainWindow", "Value1"))
        self.v2_label.setText(_translate("MainWindow", "Value2"))
        self.addButton.setText(_translate("MainWindow", "Add"))
        self.subButton.setText(_translate("MainWindow", "Subtract"))
        self.result_label.setText(_translate("MainWindow", "Result"))
        self.lineEdit.setText(_translate("MainWindow", "0"))
        self.lineEdit_2.setText(_translate("MainWindow", "0"))
        self.lineEdit_3.setText(_translate("MainWindow", "0"))
