# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ComboTest.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):

    def incrEvent(self):
        balance = int(self.lineEdit1.text())
        balance += 1
        if (balance >= 0):
            self.checkBox1.setChecked(False)
            self.lineEdit1.setText(str(balance))

    def decrEvent(self):
        balance = int(self.lineEdit1.text())
        balance -= 1
        if (balance >= 0):
            self.checkBox1.setChecked(True)
            self.lineEdit1.setText(str(balance))

    def withDrawEvent(self):
        balance = int(self.lineEdit1.text())
        amount = int(self.comboBox1.currentText())
        if (amount > balance):
            self.checkBox1.setChecked(True)
        else:
            balance -= amount
            self.lineEdit1.setText(str(balance))
            self.checkBox1.setChecked(False)

    def depositEvent(self):
        balance = int(self.lineEdit1.text())
        amount = int(self.comboBox2.currentText())
        balance += amount
        self.lineEdit1.setText(str(balance))

    def resetEvent(self):
        self.lineEdit1.setText(str(0))


    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(120, 20, 151, 51))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(80, 90, 61, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.lineEdit1 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit1.setGeometry(QtCore.QRect(200, 90, 113, 22))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lineEdit1.setFont(font)
        self.lineEdit1.setObjectName("lineEdit1")
        self.pushButton1 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton1.setGeometry(QtCore.QRect(80, 140, 93, 28))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pushButton1.setFont(font)
        self.pushButton1.setObjectName("pushButton1")
        self.comboBox1 = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox1.setGeometry(QtCore.QRect(200, 140, 73, 22))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.comboBox1.setFont(font)
        self.comboBox1.setObjectName("comboBox1")
        self.comboBox1.addItem("")
        self.comboBox1.addItem("")
        self.comboBox1.addItem("")
        self.comboBox1.addItem("")
        self.checkBox1 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox1.setGeometry(QtCore.QRect(120, 260, 161, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.checkBox1.setFont(font)
        self.checkBox1.setObjectName("checkBox1")
        self.pushButton2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton2.setGeometry(QtCore.QRect(80, 190, 93, 28))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pushButton2.setFont(font)
        self.pushButton2.setObjectName("pushButton2")
        self.comboBox2 = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox2.setGeometry(QtCore.QRect(200, 190, 73, 22))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.comboBox2.setFont(font)
        self.comboBox2.setObjectName("comboBox2")
        self.comboBox2.addItem("")
        self.comboBox2.addItem("")
        self.comboBox2.addItem("")
        self.comboBox2.addItem("")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 26))
        self.menubar.setObjectName("menubar")
        self.menuOptions = QtWidgets.QMenu(self.menubar)
        self.menuOptions.setObjectName("menuOptions")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionIncrement = QtWidgets.QAction(MainWindow)
        self.actionIncrement.setObjectName("actionIncrement")
        self.actionDecrement = QtWidgets.QAction(MainWindow)
        self.actionDecrement.setObjectName("actionDecrement")
        self.actionReset = QtWidgets.QAction(MainWindow)
        self.actionReset.setObjectName("actionReset")
        self.menuOptions.addAction(self.actionIncrement)
        self.menuOptions.addAction(self.actionDecrement)
        self.menuOptions.addAction(self.actionReset)
        self.menubar.addAction(self.menuOptions.menuAction())

        self.retranslateUi(MainWindow)
        self.actionIncrement.triggered.connect(self.incrEvent)
        self.actionDecrement.triggered.connect(self.decrEvent)
        self.pushButton1.pressed.connect(self.withDrawEvent)
        self.pushButton2.pressed.connect(self.depositEvent)
        self.actionReset.triggered.connect(self.resetEvent)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Banking App"))
        self.label_2.setText(_translate("MainWindow", "Balance"))
        self.lineEdit1.setText(_translate("MainWindow", "1000"))
        self.pushButton1.setText(_translate("MainWindow", "Withdraw"))
        self.comboBox1.setItemText(0, _translate("MainWindow", "10"))
        self.comboBox1.setItemText(1, _translate("MainWindow", "20"))
        self.comboBox1.setItemText(2, _translate("MainWindow", "50"))
        self.comboBox1.setItemText(3, _translate("MainWindow", "100"))
        self.checkBox1.setText(_translate("MainWindow", "Insufficient Funds"))
        self.pushButton2.setText(_translate("MainWindow", "Deposit"))
        self.comboBox2.setItemText(0, _translate("MainWindow", "10"))
        self.comboBox2.setItemText(1, _translate("MainWindow", "20"))
        self.comboBox2.setItemText(2, _translate("MainWindow", "50"))
        self.comboBox2.setItemText(3, _translate("MainWindow", "100"))
        self.menuOptions.setTitle(_translate("MainWindow", "Options"))
        self.actionIncrement.setText(_translate("MainWindow", "Increment"))
        self.actionDecrement.setText(_translate("MainWindow", "Decrement"))
        self.actionReset.setText(_translate("MainWindow", "Reset"))
